env:
  node: true
plugins:
  - "@babel"
  - "jest"
extends:
  - airbnb-base
  - plugin:jest/recommended
parser: "@babel/eslint-parser"
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules: {
  no-console: 0,
  no-tabs: 0,
  indent: 0,
}
