version: "3.9"

services:
  gitsecure-krios:
    image: node:14
    working_dir: /app
    container_name: gitsecure-krios
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "$PWD:/app"
    env_file:
      - ./.env
    ports:
      - 3000:3000
    command: bash -c "npm run jest src"
